version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: SHACAM-influxdb
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    

  grafana:
    image: grafana/grafana
    container_name: SHACAM-grafana
    restart: always
    volumes:
      - ./grafana/var:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: SHACAM-mqtt_broker
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config/
    ports:
    - 1883:1883 
    - 9001:9001
    

  node-red:
    image: nodered/node-red:latest
    container_name: SHACAM-nodered
    restart: always
    build:
      context: ./node-red
      dockerfile: Dockerfile
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data
    env_file:
      - .env
    depends_on:
      - mqtt_broker
    

  pyhton:
    build:
      context: ./sensors/
      dockerfile: Dockerfile
    container_name: SHACAM-pytonSensors
    restart: always


